name: Deploy Drizzle Schema

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            drizzle:
              - 'packages/database/**'
              - '.github/workflows/deploy-drizzle.yml'
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install
        if: steps.filter.outputs.drizzle == 'true'
      - run: bun run db:push
        if: steps.filter.outputs.drizzle == 'true'
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
